name: 'ansible'
description: 'runs an ansible playbook'

inputs:
  playbook:
    default: main.yml
    required: true
  verbose:
    default: 0
    required: false
  ssh-key:
    required: true

runs:
  using: docker
  image: Dockerfile
