version: "3.9"

services:
  registry:
    image: docker.io/library/registry:2.8.1@sha256:83bb78d7b28f1ac99c68133af32c93e9a1c149bcd3cb6e683a3ee56e312f1c96
    volumes:
      - /mnt/user/appdata/registry/data:/var/lib/registry
    ports:
      - 0.0.0.0:5000:5000/tcp
    networks:
      public:
        aliases:
          - registry.service.docker
    restart: always
    container_name: registry

  postgres:
    image: docker.io/library/postgres:15.2@sha256:50a96a21f2992518c2cb4601467cf27c7ac852542d8913c1872fe45cd6449947
    volumes:
      - /mnt/user/appdata/postgres/data:/var/lib/postgresql/data
    networks:
      public:
        aliases:
          - postgres.service.docker
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: postgres

  redis:
    image: docker.io/library/redis:7.0.4@sha256:e50c7e23f79ae81351beacb20e004720d4bed657415e68c2b1a2b5557c075ce0
    volumes:
      - /mnt/user/appdata/redis/data:/data
    networks:
      public:
        aliases:
          - redis.service.docker
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: redis

networks:
  public:
    driver: bridge

  private:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
