config:
  traefik:image: docker.io/library/traefik:2.11.5@sha256:eff67fb6195d2a281cad0cdb59f6f42ea6f4b99934a97188e00751d549fa5222
  traefik:namespace: kube-system
  traefik:replicas: 1
  traefik:loadBalancerIP: 10.36.0.1
  traefik:traefik.yaml: |
    log:
      level: DEBUG
    accessLog: {}
    api:
      insecure: true
      dashboard: true
    debug:
      enabled: true
    defaultEntryPoints:
      - web
      - web-secure
    entryPoints:
      web:
        address: ":80"
        transport:
          respondingTimeouts:
            readTimeout: 60
            writeTimeout: 60
      web-secure:
        address: ":443"
        transport:
          respondingTimeouts:
            readTimeout: 60
            writeTimeout: 60
        http3:
          advertisedPort: 443
      plex:
        address: ":32400/tcp"
      syncthing-tcp:
        address: ":22000/tcp"
      syncthing-udp:
        address: ":22000/udp"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        ingressClass: traefik-cert-manager
    experimental:
      http3: true
      kubernetesGateway: true
  kubernetes:context: k3s
