services:

  filen:
    image: filen/cli:v0.0.39
    command:
      - s3
      - --s3-host=0.0.0.0
      - --s3-port=80
      - --s3-access-key-id=${AWS_ACCESS_KEY_ID}
      - --s3-secret-access-key=${AWS_SECRET_ACCESS_KEY}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ../.filen-cli-auth-config:/filen-cli/.filen-cli-auth-config:ro
    networks:
      homelab:
        aliases:
          - filen.homelab.docker.local

  pulumi:
    build:
      context: ./
    working_dir: /workspace/
    environment:
      - PULUMI_BACKEND_URL
      - PULUMI_CONFIG_PASSPHRASE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - pulumi-cache:/home/pulumi/.pulumi/:rw
      - ./projects/:/workspace/projects/:rw
      - ./resources/:/workspace/resources/:rw
      - ~/.kube/config:/home/pulumi/.kube/config:ro
    networks:
      - homelab
    depends_on:
      - filen

volumes:
  pulumi-cache: {}
