api:
  dashboard: true
  insecure: false

pilot:
  dashboard: false

global:
  sendAnonymousUsage: false
  checkNewVersion: false

log:
  level: DEBUG

accessLog:
  format: json

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik.yml"

entryPoints:
  http:
    address: ':80/tcp'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ':443/tcp'

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: http
      email: kurt@unkn.co
      storage: /config/acme.json

http:
  middlewares:
    authentik:
      forwardAuth:
        address: http://authentik-server.service.docker:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
