docker  := `which docker`
compose := docker + ' compose -p homelab --progress plain -f ../compose.yaml'
ansible := compose + ' run ansible '

shell:
  {{ansible}} /bin/sh

inventory *ARGS='--list':
  {{ansible}} ansible-inventory {{ARGS}}

playbook *ARGS:
  {{ansible}} ansible-playbook {{ARGS}}

vault *ARGS:
  {{ansible}} ansible-vault {{ARGS}}
