---

- name: common host provisioning
  hosts: all
  roles:
    - common
  become: true
  gather_facts: true
  tags:
    - common

- name: wireguard client provisioning
  hosts: external
  roles:
    - wireguard
  become: true
  gather_facts: true
  tags:
    - wireguard

- name: k3s cluster provisioning
  hosts: cluster
  roles:
    - k3s
  serial:
    - 1
    - "100%"
  become: true
  gather_facts: true
  tags:
    - k3s

- name: nas storage provisioning
  hosts: nas
  roles:
    - nas
  become: true
  gather_facts: true
  tags:
    - nas
