name: ansible

on:
  push:
    branches:
    - master
    - ansible

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/ansible
      with:
        playbook: infrastructure/ansible/main.yml
